### ISSUE TITLE
Not an issue but just to say thank you!

### ISSUE THREAD

**Issue by kar200** [mhdzli/dotfiles#3]
Hi there,

This is just to say thank you for the dotfiles. I have reinstalled arch+sway more times than I can count and since using your dotfiles (came from waybar) I have to say they are the best for a simple yet useful config.

I don't use the whole thing obviously but mainly your sway config and your bin folder.

I am not sure if you are using arch but the reboot and shutdown commands can be passed through (reboot) and (poweroff) which doesn't need to use sudo (if it's more generic then disregard the comment).

I am also interested in the bin folder with the scripts in it. did you write te scripts yourself or is there some sort of repo where we can find these useful scripts?

Thanks again for sharing and have a good day.

K.

**Comment by mhdzli** [comment]
@kar200 
First of all your welcome, it's so nice of you. Most of them are inspired by other's work. If you are interested  these are some useful beginning points:

[I3 migration guide on swaywm wiki](https://github.com/swaywm/sway/wiki/i3-Migration-Guide)

[Drew DeVault (swaywm maintainer)'s dotfiles](https://git.sr.ht/~sircmpwn/dotfiles)

@terminalforlife the ultimate master of shell scripts: https://github.com/terminalforlife/ and his amazing [youtube channel](https://www.youtube.com/channel/UCfp-lNJy4QkIGnaEE6NtDSg)

[Dylan's github page](https://github.com/dylanaraps)

[Kai Hendry's dotfile](https://github.com/kaihendry/dotfiles)

[lukesmithxyz](https://github.com/lukesmithxyz/)'s work on his [voidrice](https://github.com/LukeSmithxyz/voidrice)

[Drek Taylor's  dotfiles](https://gitlab.com/dwt1/dotfiles) witch has the config for almost every window manager on X

And there are many more 😁
