### ISSUE TITLE
Redirect from waybar examples not correct anymore

### ISSUE THREAD

**Issue by kar200** [mhdzli/dotfiles#4]
Hi again,

Since you have changed your folder structure the link from the waybar wiki does not redirect correctly anymore.

https://github.com/Alexays/Waybar/wiki/Examples

Also in your fonts.conf you have an extra "P".

Have a good day.

**Comment by mhdzli** [comment]
@kar200 

Welcome again and  many thanks. Finding that "P" was strangely hard even when I knew it was there :).
I updated the waybar wiki and added a new screenshot.

**Comment by mhdzli** [comment]
@kar200 
And there is also a [rootbar](https://hg.sr.ht/~scoopta/rootbar) for sway.

**Comment by kar200** [comment]
@mhdzli 
Thanks I will have a look at rootbar. To be honest I use i3status-rust instead of waybar at the moment.
